theme: jekyll-theme-minimal
title: "MageLock's Site"
description: "<a href='https://www.youtube.com/@MageLock'>My YouTube channel</a><br><a href='https://notmagelock.github.io/Pages/gamepage.html'>Games</a>"
